### ISSUE TITLE
[this](https://github.com/Stringier/Patterns/issues/41) and [this](https://github.com/Stringier/Core/issues/81) describe an issue with zwsp along with the debate around it. I've settled on a solution involving keeping the `Cf` classification instead of `Zs`, but also ensuring that it is detected as a word boundary. So zwsp (U+200B) absolutely must be recognized that way.

### ISSUE THREAD

**Issue by gearshead** [Stringier/Literary#21]
[this](https://github.com/Stringier/Patterns/issues/41) and [this](https://github.com/Stringier/Core/issues/81) describe an issue with zwsp along with the debate around it. I've settled on a solution involving keeping the `Cf` classification instead of `Zs`, but also ensuring that it is detected as a word boundary. So zwsp (U+200B) absolutely must be recognized that way.

_Originally posted by @Entomy in https://github.com/Stringier/Literary/issues/13#issuecomment-608387154_

**Comment by Entomy** [comment]
This is a duplicate of #13, so I'm closing this. The comment this is based on details a specific, atypical, behavior, that needs to be met when resolving this issue. This makes it a requirement, not its own issue.
