### ISSUE TITLE
Reduce the number of conditional operators (4) used in the expression (maximum allowed 3).

### ISSUE THREAD

**Issue by Entomy** [Stringier/Literary#6]
#### Occurred on:
+ **Commit**:  a483b809149d6f0bb9e1a168524e115d4894eaad
+ **File**:    [Literary/IsPalindrome.cs](https://github.com/Entomy/Stringier-Literary/blob/a483b809149d6f0bb9e1a168524e115d4894eaad/Literary/IsPalindrome.cs)
+ **LineNum**: [55](https://github.com/Entomy/Stringier-Literary/blob/a483b809149d6f0bb9e1a168524e115d4894eaad/Literary/IsPalindrome.cs#L55)
+ **Code**:    `if (!(Char.IsControl(s) || Char.IsPunctuation(s) || Char.IsSeparator(s) || Char.IsSymbol(s) || Char.IsWhiteSpace(s))) {`

    
#### Currently on:
+ **Commit**:  367b885ab6723c29f2605f46edcf87cc74d78394
+ **File**:    [Literary/IsPalindrome.cs](https://github.com/Entomy/Stringier-Literary/blob/367b885ab6723c29f2605f46edcf87cc74d78394/Literary/IsPalindrome.cs)
+ **LineNum**: [55](https://github.com/Entomy/Stringier-Literary/blob/367b885ab6723c29f2605f46edcf87cc74d78394/Literary/IsPalindrome.cs#L55)

**Comment by Entomy** [comment]
This may be something that can be optimized. It's hard to tell, because regardless, there's going to be a buttload of checks for this.

**Comment by arogers7** [comment]
Do you think something like `if (! listOfForbiddenChars.Contains(s))` would be an improvement?

**Comment by Entomy** [comment]
Visually yes, absolutely. And it would certainly hush the analyzer.

 My only concern with that is, as this is part of a text system which is increasingly globally compliant, that such an approach might be missing key characters. As long as it works, I'll accept it.

**Comment by Entomy** [comment]
Closed by #7
